public with sharing class TimeTrackerConstants {

    public static final String TASK = 'Task';
    public static final String TASK_SAVE = 'Task Save';
    public static final String TASK_CANCEL = 'Task Cancel';
    public static final String EVENT = 'Event';
    public static final String EVENT_SAVE = 'Event Save';
    public static final String EVENT_CANCEL = 'Event Cancel';
    public static final String SEND_EMAIL = 'Send an Email';
    public static final String SEND_EMAIL_SAVE = 'Send an Email Save';
    public static final String SEND_EMAIL_CANCEL = 'Send an Email Cancel';
    public static final String LOG_CALL = 'Log a Call';
    public static final String LOG_CALL_SAVE = 'Log a Call Save';
    public static final String LOG_CALL_CANCEL = 'Log a Call Cancel';
    public static final String ATTACH_FILE = 'Attach File';
    public static final String ATTACH_FILE_SAVE = 'Attach File Save';
    public static final String ATTACH_FILE_CANCEL = 'Attach File Cancel';
    public static final String CASE_COMMENT = 'Case Comment';
    public static final String CASE_COMMENT_SAVE = 'Case Comment Save';
    public static final String CASE_COMMENT_CANCEL = 'Case Comment Cancel';
    public static final String CASE_TAB = 'Case Tab';
    public static final String TIME_TRACKER_PERMISSION_SET_NAME = 'Time Tracker Permission Set';
    public static final String TIME_TRACKER_ADMIN_PERMISSION_SET_NAME = 'Time Tracker Admin Permission Set';
    public static final String TIME_TRACKER_ADMIN_PERMISSION_SET_API_NAME = 'Time_Tracker_Admin_Permission_Set';
    public static final String MISCELLANEOUS_MAX_TIME_CONSIDERIN_MIN = 'Miscellaneous_maxTimeConsiderInMin';
    public static final String MISCELLANEOUS_EXECUTE_TRIGGERS = 'Miscellaneous_executeTriggers';

    public static final String NEW_STR = 'New';
    public static final String REJECTED_STR = 'Rejected';
    public static final String RECALLED_STR = 'Recalled';
    public static final String SUBMITTED_STR = 'Submitted';
    public static final String APPROVED_STR = 'Approved';
    
    public static final String TIME_TRACKER_STRATEGY_STR = 'Strategies';
    public static final String TIME_TRACKER_MAX_TIME_CONSIDER_IN_MIN = 'MaxTimeConsiderInMin';
    public static final String TIME_TRACKER_EXECUTE_TRIGGER = 'executeTriggers';    
    public static final String TIME_SPENT_DEFAULT_VALUE = '00:00:00';
    public static final String IMPLEMENATION_CLASS_NAME_SUFFIX = 'Impl';
    public static final String TimeTracker_runTimeTrackerTriggers = 'RunTimeTrackerTriggers';

    //TimeTracker create-new implementation constants
    public static final String HISTORY_REVIEW = 'History Review';
    public static final String CHATTER_TOPIC_PAGE_REVIEW = 'Chatter topic page Review';
    public static final String CHATTER_REVIEW = 'Chatter Review';
    public static final String SENDING_EMAIL_USING_EMAIL_AUTHOR = 'Sending Email using Email Author';
    public static final String SEARCH_PAGE = 'Search Page';
    public static final String CHANGE_PASSWORD = 'Change Password';
    public static final String ACCOUNT_HIERARCHY_REVIEW = 'Account Hierarchy Review';
    public static final String ACCOUNT_TEAM_MEMBERS_REVIEW = 'Account Team Members Review';
    public static final String CONNECTIVITY_REVIEW = 'Connectivity Review';
    public static final String ATTACHMENTS_REVIEW = 'Attachments Review';
    public static final String EMAIL_STATUS_CHECK = 'Email Status Check';
    public static final String PROCESS_WORK_ITEM_WIZARD = 'Process Work Item Wizard';
    public static final String SUBMIT_PROCESS = 'Submit Process';
    public static final String LOGIN_TO_PORTAL = 'Login to Portal';
    public static final String RECORD_TYPE_SELECTION = 'Record type selection';
    public static final String SEARCH_FOR_CONTENT = 'Search For Content';
    public static final String VIEW_ALL_ATTACHMENT = 'View All Attachment';
    public static final String EMAIL_MESSAGES_REVIEW = 'Email Messages Review';
    public static final String SOLUTION_SEARCH = 'Solution Search';
    public static final String NEW_CASE_FROM_CREATENEW = 'New Case';
    public static final String TCEntry = 'TC Entry';

    // TimeTracker opening actions
    public static final String NEW_CASE_STR = 'New Case';
    public static final String NEW_CASE_CANCEL = 'Cancel New Case';
    public static final String NEW_CASE_CANCELATION = 'Case Cancel';
    public static final String CASE_DETAIL_STR = 'Case Detail';
    public static final String CLOSE_SUBTAB_STR = 'Close SubTab';
    public static final String REVIEW_CHAT_VISITOR_DETAILS = 'Review Chat Visitor Details';
    public static final String CHAT_AUTO_SEARCH = 'Chat Auto Search';

    // Chatter Posts
    public static final String CHATTER_TEXT_POST = 'Chatter Text';
    public static final String CHATTER_SEND_EMAIL_POST = 'Chatter Send Email';
    public static final String CHATTER_LOG_CALL_POST = 'Chatter Log a Call';
    public static final String CHATTER_CHANGE_CASE_STATUS_POST = 'Chatter Change Case Status';
    public static final String CHATTER_FILE_POST = 'Chatter File';
    public static final String CHATTER_LINK_POST = 'Chatter Link';
    public static final String CHATTER_THANK_YOU_POST = 'Chatter Thank You';
    public static final String CHATTER_POLL_POST = 'Chatter Poll';
    public static final String CHATTER_QUESTION_POST = 'Chatter Question';

    public static final String CHATTER_TEXT_POST_STP = 'End Chatter Text Post';
    public static final String CHATTER_SEND_EMAIL_POST_STP = 'End Chatter Send Email Post';
    public static final String CHATTER_LOG_CALL_POST_STP = 'End Chatter Log Call Post';
    public static final String CHATTER_CHANGE_CASE_STATUS_POST_STP = 'End Chatter Change Case Status Post';
    public static final String CHATTER_FILE_POST_STP = 'End Chatter File Post';
    public static final String CHATTER_LINK_POST_STP = 'End Chatter Link Post';
    public static final String CHATTER_THANK_YOU_POST_STP = 'End Chatter Thank You Post';
    public static final String CHATTER_POLL_POST_STP = 'End Chatter Poll Post';
    public static final String CHATTER_QUESTION_POST_STP = 'End Chatter Question Post';

    public static final String EDIT_CASE_STR = 'Edit Case';
    public static final String EDIT_CASE_SAVED = 'Edit Case Saved';

    public static final String CLOSE_CASE_STR = 'Close Case';
    public static final String CANCEL_CLOSE_CASE = 'Case close Cancel';
    public static final String CLOSE_TAB_STR = 'Close Tab';
    public static final String CLOSE_CASE_SAVE_STR = 'Case close Save';
    public static final String POST_CASE_COMMENT_STR = 'Post Case Comment';
    public static final String WRITE_CASE_NOTE_STR = 'Write Case Note';
    public static final String WRITE_CASE_NOTE_END_STR = 'Write Case Note End';
    public static final String NEW_ARTICLE_STR = 'New Article';
    public static final String NEW_ARTICLE_CANCEL =  'New Article Cancel';
    public static final String EDIT_ARTICLE = 'Edit Article';
    public static final String EDIT_ARTICLE_CANCEL = 'Edit Article Cancel';
    public static final String NEW_ARTICLE_SAVED_CLOSED = 'New Article SaveClosed';
    public static final String OPEN_PRIMARY_CASE_TAB_STR = 'Opened Primary Case Tab';
    public static final String OPEN_PRIMARY_OTHER_TAB_STR = 'Opened Other Primary Tab';
    public static final String OPEN_OTHER_SUBTAB = 'Opened Other SubTab';
    public static final String CASE_OPENED_FOR_REVIEW = 'Case Opened For Review';
    public static final String START_CHAT_STR = 'Start Chat';
    public static final String ADD_CASE_COMMENT = 'Add Case Comment';
    public static final String ADD_CASE_COMMENT_SAVE = 'Add Case Comment Save';
    public static final String ADD_NEXT_ACTION_DATE = 'Add Next Action Date';
    public static final String CASE_FOLLOW_UP = 'Case Followup';
    public static final String NEXT_ACTION_DATE_ADDED = 'Next Action Date Added';
    public static final String CHANGE_CASE_STATUS = 'Change Case Status';
    public static final String CASE_STATUS_CHANGED = 'Case Status Changed';
    public static final String CHANGE_ASSET_STR = 'Change Asset';
    public static final String CANCEL_CHANGE_ASSET = 'Change Asset Cancel';
    public static final String ESCALATE_L3_STR = 'Escalate to L3';
    public static final String ESCALATED_L3_STR = 'Escalated to L3';
    public static final String ESCALATION_STR = 'Escalation start';
    public static final String ESCALATION_SAVED = 'Escalation saved';
    public static final String CASE_LIST_VIEW = 'Cases List View';
    public static final String CASE_NAVIGATION_EXIT ='Cases Navigation Tab Exit';
    public static final String CHATTER_LIST_VIEW = 'Chatter List View';
    public static final String CHATTER_NAVIGATION_EXIT = 'Chatter Navigation Tab Exit';
    public static final String REPORTS_LIST_VIEW = 'Reports List View';
    public static final String REPORTS_NAVIGATION_EXIT = 'Reports Navigation Tab Exit' ;
    public static final String DASHBOARDS_LIST_VIEW = 'Dashboards List View';
    public static final String DASHBOARDS_NAVIGATION_EXIT ='Dashboards Navigation Tab Exit';
    public static final String TIMESHEETS_LIST_VIEW = 'Timesheets List View';
    public static final String TIMESHEETS_NAVIGATION_EXIT = 'Timesheets Navigation Tab Exit';
    public static final String LIVE_AGENT_SUPERVISOR = 'Live Agent Supervisor List View';
    public static final String LIVE_AGENT_SUPERVISOR_EXIT = 'Live Agent Supervisor Exit';
    public static final String LIVE_CHAT_TRANSCRIPTS_LST = 'Live Chat Transcripts List View';
    public static final String LIVE_CHAT_TRANSCRIPTS_Lst_EXIT = 'Live Chat Transcripts Exit';
    public static final String NEW_TASK_SAVE = 'New Task Saved';
    public static final String LOG_A_CALL = 'Log a Call';
    public static final String LOG_A_CALL_SAVED = 'Log a Call Saved';
    public static final String OPEN_SECONDARY_CASE_SUBTAB = 'Opened Secondary Case SubTab';
    public static final String CLOSE_SECONDARY_CASE_SUBTAB = 'Close Secondary Case SubTab';
    //public static final String ATTACH_FILE = 'Attach File';
    public static final String NEW_TASK = 'New Task';
    public static final String ANSWER_CUSTOMER_STR = 'Case Email Start';
    public static final String ANSWER_CUSTOMER_SENT = 'Email Sent Successfully';
    public static final String SEND_EMAIL_COMPLETE = 'Send Email Complete';
    public static final String SEND_EMAIL_START = 'Send Email Start';
    public static final String CHANGE_CASE_OWNER_STR = 'Change Case Owner';
    public static final String CASE_OWNER_CHANGED_STR = 'Case Owner Changed';
    public static final String REVIEEW_CHAT_TRANSCRIPT = 'Reviewing a transcript';
    public static final String OTHER_ACTIVITIES = 'Other Activities';
    public static final String MASS_CLOSE_CASE = 'Mass Close Case';
    public static final String CANCEL_MASS_CLOSE_CASE = 'Cancel Mass Close Case';
    public static final String MASS_CHANGE_OWNER = 'Mass Change Owner';
    public static final String CANCEL_MASS_CHANGE_OWNER = 'Cancel Mass Change Owner';
    public static final String MASS_CHANGE_STATUS = 'Mass Change Status';
    public static final String CANCEL_MASS_CHANGE_STATUS = 'Cancel Mass Change Status';
    public static final String ATTACH_ARTICLE = 'Attach Article';
    public static final String ARTICLE_ATTACH = 'Article Attach';
    public static final String ATTACH_ARTICLE_COMPLETE = 'Attach Article Complete';
    public static final String CREATE_NEW = 'Create New';
    public static final String OPENED_FOR_REVIEW = 'Opened for Review';
    public static final String REVIEW = 'Review';
    public static final String CREATION = 'Creation';

    // TimeTracker closing actions
    public static final String SAVE_STR = 'Save';
    public static final String SAVE_AND_CLOSE_STR = 'Save & Close';
    public static final String CANCEL_STR = 'Cancel';
    public static final String DELETE_STR = 'Delete';
    public static final String CLOSE_STR = 'Close';
    public static final String END_CHAT_STR = 'End Chat';
    public static final String CANCEL_CHAT_STR = 'Cancel Chat';
    public static final String DECLINE_CHAT_STR = 'Decline Chat';
    public static final String TRANSFER_CHAT_STR = 'Transfer Chat';
    public static final String ESCALATE_L3_CANCEL_STR = 'Escalate to L3 -Cancel';
    public static final String ATTACH_FILE_COMPLETED_STR = 'Attach File Completed';

    // TimeTracker activity
    public static final String CASE_WORK_STR = 'Case Work';
    public static final String NON_CASE_WORK_STR = 'Non-Case Work';
    public static final String HOUSEKEEPING_STR = 'Housekeeping';

    // TimeTracker Action Category
    public static final String MANUAL_STR = 'Manual';
    public static final String MANUAL_BREAK = 'Manual_Break';

    // Timesheet Entry activity
    public static final String CASE_CREATION_STR = 'Case Creation';
    public static final String CASE_DOCUMENTATION_STR = 'Case Documentation';
    public static final String CANCELLED_DOCUMENTATION = 'Cancelled Documentation';
    public static final String CASE_REVIEW_STR = 'Case Review';
    public static final String ARTICLE_ATTACHMENT = 'Article Attachment';
    public static final String ARTICLE_CREATION_STR = 'Article Creation';
    public static final String ARTICLE_MAINTENANCE = 'Article Maintenance';
    public static final String ARTICLE_CANCELLATION = 'Article Cancellation';
    public static final String CANCEL_NEW_ARTICLE= 'Cancel New Article';
    public static final String CANCELLED_NEWARTICLE = 'New Article Cancel';
    public static final String CANCEL_EDIT_ARTICLE = 'Cancel Edit Article';
    public static final String CANCELLED_EDITARTICLE = 'Edit Article Cancel';
    public static final String CUSTOMER_CHAT_STR = 'Customer Chat';
    public static final String CLOSE_CASE_ACTIVITY_STR = 'Case Closure';
    public static final String CASE_ASSIGNMENT_STR = 'Case Assignment';
    public static final String CANCEL_DOCUMENTATION_STR = 'Canceled Documentation';
    public static final String LEVEL_3_STR = 'Level 3';
    public static final String CHAT_SUPERVISOR = 'Chat Supervisor';
    public static final String CUSTOMER_ESCALATION_STR = 'Customer Escalations';
    public static final String TASK_CREATION = 'Task Creation';
    public static final String CHATTER = 'Chatter';
    public static final String REPORTING = 'Reporting';
    public static final String TIME_TRACKING = 'Time Tracking';
    public static final String CUSTOMER_ESCALATIONS = 'Customer Escalations';
    public static final String QUEUE_MONITORING = 'Queue Monitoring';
    public static final String EMAIL_STR = 'Email';

    // Date format
    public static final String TIMESHEET_NAME_DATE_FORMAT = 'yyyyMMdd';
    public static final String TIMESHEETENTRY_UNIQUE_DATE_FORMAT = 'yyyyMMdd';

    // Error message

    // Test class related
    public static final String SYSTEM_STR = 'System';

    //time tracker setting constants
    public static final String LOG_USER_ID = 'log_user_id';
    public static final String LOG_TYPE_DEFAULT = 'log_type_default';
    public static final String HTML_CUSTOM = 'html_custom';
    public static final String DEBUG = 'debug';
    public static final String HTML_TAG = 'html_tag';
    public static final String LOG_TYPE = 'log_type';
    public static final String URL_CASE = 'url_case';
    public static final String HTML_CLASS = 'html_class';
    public static final String HTML_INPUT_TYPE = 'html_input_type';
    public static final String PUSH_INTERVAL = 'push_interval';

    //Manual-Activities
    public static final String BREAKs = 'Break';
    public static final String EMAIL = 'Email';
    public static final String ENROLLMENT = 'Enrollment';
    public static final String GENERAL_OTHER = 'General - Other';
    public static final String MEETING = 'Meeting';
    public static final String MENTORING = 'Mentoring';
    public static final String OPEREATIONS = 'Operations';
    public static final String OUT_OF_OFFICE = 'Out of Office';
    public static final String POINT_OF_ESCALATION = 'Point of Escalation';
    public static final String PROJECT_WORK = 'Project Work';
    public static final String SHADOWING_CUSTOMER = 'Shadowing Customer';
    public static final String TRAINING_CONSUMING = 'Training - Consuming';
    public static final String TRAINING_DELIVERRING = 'Training - Delivering';
    public static final String WORK_STOPPAGE = 'Work Stoppage';

    //TimeTracker config settings Types
    public static final String CUSTOM_EVENT_TYPE = 'Custom Event';
    public static final String MANUAL_TYPE = 'Manual';
    public static final String STRATEGY_TYPE = 'Strategy';
    public static final String URL_PATTERN_TYPE = 'URLPattern';
    public static final String MISCELLANEOUS = 'Miscellaneous';
    public static final String OBJECT_SETTINGS = 'Object Settings';
    
    // to un-hardcode strings
    public static final String TEXT1_FIELD = 'Text1__c';
    public static final String CODE1_FIELD = 'Code1__c';
    public static final String OBJECTID_FIELD = 'Object_Id__c';
    public static final String PARENT_OBJECTID_FIELD = 'Parent_Object_Id__c';
    public static final String TRUE_TEXT = 'true';
    public static final String ERROR_OCCURRED_TEXT = 'Error_Occured';
    public static final String LOCKED_TEXT = 'Locked';
    public static final String FALSE_TEXT = 'false';
    public static final String CONFIG_SETTING_FILE_NAME = 'TimeTrackerConfigSettings_Records';
    
    // Validation Error on timesheet submit
    public static final String ERROR_TIMESHEET_LOCKED = 'Timesheet of the week of Activity Date is approved or under approval process. No new time can be entered for the timesheet.';
}